// Generated by ReScript, PLEASE EDIT WITH CARE


var arraify_helper = ((json) => Object.entries(json));

function from_url(url) {
  return {
          url: url,
          body: undefined
        };
}

function set_params(request, params) {
  return {
          url: request.url.concat("?").concat(arraify_helper(params).map(function (param) {
                      return param[0] + "=" + param[1];
                    }).join("&")),
          body: request.body
        };
}

function set_body(request, body) {
  return {
          url: request.url,
          body: JSON.stringify(body)
        };
}

async function get(request) {
  var res = await fetch(request.url);
  if (!res.ok) {
    return {
            TAG: "Error",
            _0: res.status
          };
  }
  var json = await res.json();
  return {
          TAG: "Ok",
          _0: json
        };
}

async function post(request) {
  var body = request.body;
  var res = await fetch(request.url, {
        body: body !== undefined ? body : "",
        headers: {
          "Content-Type": "application/json"
        },
        method: "POST"
      });
  if (!res.ok) {
    return {
            TAG: "Error",
            _0: res.status
          };
  }
  var json = await res.json();
  return {
          TAG: "Ok",
          _0: json
        };
}

export {
  arraify_helper ,
  from_url ,
  set_params ,
  set_body ,
  get ,
  post ,
}
/* No side effect */
