// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http$RescriptHttp from "../lib/Http.res.js";

var url = "https://jsonplaceholder.typicode.com/posts/1";

var page = await Http$RescriptHttp.$$delete(Http$RescriptHttp.from_url(url, undefined));

console.log(page._0);

export {
  url ,
  page ,
}
/* page Not a pure module */
