// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Http from "./lib/Http.res.js";

function post_example() {
  return Http.post(Http.set_body(Http.from_url("https://jsonplaceholder.typicode.com/posts"), {
                  name: 12312.1,
                  major: "CS"
                }));
}

function get_example() {
  return Http.get(Http.set_params(Http.from_url("https://jsonplaceholder.typicode.com/posts/1"), {
                  page: 2,
                  limit: 50
                }));
}

var post_result = await post_example();

if (post_result.TAG === "Ok") {
  console.log("do some with", post_result._0);
} else {
  console.error("Something went wrong");
}

var get_result = await get_example();

if (get_result.TAG === "Ok") {
  console.log("do some with", get_result._0);
} else {
  console.error("Something went wrong");
}

var $$Request;

export {
  $$Request ,
  post_example ,
  get_example ,
  post_result ,
  get_result ,
}
/* post_result Not a pure module */
